# url home
opencart.home=https://opencart.abstracta.us
opencart.webdriver = webdriver.chrome.driver
opencart.driver = ./src/test/resources/chromedriver/chromedriver.exe
linkProductLocator = //a[contains(text(), 'iPhone')]